build:
  image: ruby:2.2-alpine
  commands:
    - apk --update add build-base openssl-dev
    - bundle install
publish:
  gcr:
    registry: eu.gcr.io
    repo: potent-pursuit-88116/drone-demo
    storage_driver: overlay
    token: >
      $$GCR_TOKEN
