build:
  image: ruby:2.2-alpine
  commands:
    - apk --update add build-base openssl-dev
    - bundle install
publish:
  gcr:
    when:
      branch: master
    registry: eu.gcr.io
    repo: potent-pursuit-88116/drone-demo
    storage_driver: overlay
    token: >
      $$GCR_TOKEN
notify:
  webhook:
    when:
      branch: master
    urls:
      - https://aws-master-1.kontena.io/v1/services/aws-coreos/drone-demo/deploy
    content_type: application/json
    header:
      Authorization: Bearer $$KONTENA_TOKEN
    template: >
      {}
